# This is the manifest that gives parameters for the generation
# process.
apiVersion: cuttlefacts/v1
kind: AppDeploy
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: cuttlefacts/app-template:0.2.0
    fluxcd.io/ignore: true
  name: myapp
  namespace: myapp
spec:
  deploy:
    # Path to the YAMLs, within the deploy git repo
    path: deploy/
    # HTTPS URL to the git repo with app deployment YAMLs
    url: https://github.com/cuttlefacts/myapp.git
  ingress:
    # URL path under which to serve the app; must start with '/' but
    # not end with it (it gets interpolated into a pattern)
    prefix: /myapp
    # name of the service to forward requests to
    serviceName: service
    # port on the service to forward requests to
    servicePort: 8080

