# This is the manifest that gives parameters for the generation
# process.
apiVersion: cuttlefacts/v1
kind: AppBuild
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: cuttlefacts/app-template:0.2.2
    fluxcd.io/ignore: true
  name: myapp
  namespace: myapp
spec:
  image:
    # Path within the git repo to a Dockerfile to build
    dockerfilePath: Dockerfile
    # the path to the Docker build context
    path: src/
    # this refers to a secret to be supplied by the package user, in
    # the platform-system namespace
    pushSecret: myapp-push-secret
    # the image repo
    repo: cuttlefacts/myapp
    # HTTPS URL to the git repo with app source code
    url: https://github.com/cuttlefacts/myapp.git
  hooks:
    githubSharedKey: myapp-github-key
