---
# This service account is needed because event listeners must run with
# a serviceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: APP-serviceaccount
  namespace: platform-system
secrets: # NB see local/README.md regarding secrets
- name: APP-push-secret
