## This contains Tekton Triggers definitions particular to the
## app. These do not live in the app namespace; they just drive
## delivery for that things in that namespace.
---
# These bindings hardcode some of the fields that we (mostly) do not
# want to take from the payload
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: APP-push-binding
  namespace: platform-system
spec:
  params:
  - name: gitrepositoryurl
    value: https://github.com/cuttlefacts/APP
  - name: dockerfile
    value: src/Dockerfile
  - name: path
    value: src/
  - name: imagename
    value: cuttlefacts/APP:$(body.head_commit.id)
  - name: serviceaccount
    value: APP-serviceaccount
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: APP-merge-listener
  namespace: platform-system
spec:
  serviceType: ClusterIP
  serviceAccountName: APP-serviceaccount # somewhat arbitrarily
  triggers:
  - name: master-merge
    interceptors:
    - github:
        secretRef:
          secretName: APP-github-secret
          secretKey: key
        eventTypes:
          - push
    - cel:
        filter: "body.ref == 'refs/heads/master'"
    bindings:
    - ref: github-push-binding
    - ref: APP-push-binding
    template:
      name: build-image-template
