apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.6.0
    version: v0.6.0
  name: eventlisteners.triggers.tekton.dev
spec:
  additionalPrinterColumns:
  - JSONPath: .status.address.url
    name: Address
    type: string
  - JSONPath: .status.conditions[?(@.type=='Available')].status
    name: Available
    type: string
  - JSONPath: .status.conditions[?(@.type=='Available')].reason
    name: Reason
    type: string
  group: triggers.tekton.dev
  names:
    categories:
    - tekton
    - tekton-triggers
    kind: EventListener
    plural: eventlisteners
    shortNames:
    - el
    singular: eventlistener
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
