apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-triggers
    triggers.tekton.dev/release: v0.6.0
  name: triggers-webhook-certs
  namespace: tekton-pipelines # {"$kpt-set":"namespace"}
